Transform: AWS::Serverless-2016-10-31
Description: Chatapp Tokens serverless template.
Parameters:
  RenewStateMachineName:
    Type: String
    Default: ChatappTokensRenew
    Description: The name of the renew state machine.
  ChatappTokensTableNameTokens:
    Type: String
    Default: ChatappTokensTokens
    Description: The name of the table for the tokens of Chatapp Tokens.
  ChatappTokensTableNameScheduler:
    Type: String
    Default: ChatappTokensScheduler
    Description: The name of the table for the scheduler of Chatapp Tokens.
Globals:
  Function:
    Timeout: 20
    MemorySize: 640
    Environment:
      Variables:
        CONFIG_PARAM_KEY: /chatapp-tokens/dev/encrypted
        TABLE_NAME_TOKENS:
          Ref: ChatappTokensTableTokens
        TABLE_NAME_SCHEDULER:
          Ref: ChatappTokensTableScheduler
        DB_ENDPOINT_OVERRIDE: ''
        OVERRIDE_DB_ENDPOINT: 'false'
        RENEW_STATE_MACHINE:
          Fn::Sub:
          - arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${RenewStateMachineName}
          - RenewStateMachineName:
              Ref: RenewStateMachineName
        STATE_MACHINE_ENDPOINT_OVERRIDE: ''
        OVERRIDE_STATE_MACHINE_ENDPOINT: 'false'
Resources:
  GetTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      KmsKeyArn:
        Fn::GetAtt:
        - ParameterStoreEncryptionKey
        - Arn
      CodeUri: s3://nexmo-tokens/b44b568372f6aa44e7cd2f8b34715651
      Runtime: java8
      Handler: com.chatapp.tokens.handlers.get.GetHandler
      Role:
        Fn::GetAtt:
        - ParameterStoreDynamoDBRole
        - Arn
      Events:
        GetToken:
          Type: Api
          Properties:
            Path: /{provider}/{externalId}
            Method: get
  CreateTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      KmsKeyArn:
        Fn::GetAtt:
        - ParameterStoreEncryptionKey
        - Arn
      CodeUri: s3://nexmo-tokens/b44b568372f6aa44e7cd2f8b34715651
      Runtime: java8
      Handler: com.chatapp.tokens.handlers.create.CreateHandler
      Role:
        Fn::GetAtt:
        - ParameterStoreDynamoDBRole
        - Arn
      Events:
        CreateToken:
          Type: Api
          Properties:
            Path: /create/{provider}
            Method: post
  RenewTokenFunctionAPI:
    Type: AWS::Serverless::Function
    Properties:
      KmsKeyArn:
        Fn::GetAtt:
        - ParameterStoreEncryptionKey
        - Arn
      CodeUri: s3://nexmo-tokens/b44b568372f6aa44e7cd2f8b34715651
      Runtime: java8
      Handler: com.chatapp.tokens.handlers.renew.RenewHandlerAPI
      Role:
        Fn::GetAtt:
        - ParameterStoreDynamoDBRole
        - Arn
      Events:
        RenewTokenAPI:
          Type: Api
          Properties:
            Path: /renew/{provider}/{externalId}
            Method: post
  RenewTokenFunctionStateMachine:
    Type: AWS::Serverless::Function
    Properties:
      KmsKeyArn:
        Fn::GetAtt:
        - ParameterStoreEncryptionKey
        - Arn
      CodeUri: s3://nexmo-tokens/b44b568372f6aa44e7cd2f8b34715651
      Runtime: java8
      Handler: com.chatapp.tokens.handlers.renew.RenewHandlerStateMachine
      Role:
        Fn::GetAtt:
        - ParameterStoreDynamoDBRole
        - Arn
  ParameterStoreDynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - states.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonSNSFullAccess
      Policies:
      - PolicyName: ParameterStoreChatappTokensDev
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ssm:GetParameter*
            Resource:
              Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/chatapp-tokens/dev*
      - PolicyName: LambdaInvoke
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeAsync
            - lambda:InvokeFunction
            Resource: '*'
      - PolicyName: StateMachineStartExecution
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - states:StartExecution
            Resource: '*'
  ParameterStoreEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/chatapp-tokens/dev
      TargetKeyId:
        Ref: ParameterStoreEncryptionKey
  ParameterStoreEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
        - Sid: Allow administration of the key
          Effect: Allow
          Principal:
            AWS:
            - Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
          Action:
          - kms:*
          Resource: '*'
        - Sid: Allow use of the key
          Effect: Allow
          Principal:
            AWS:
              Fn::GetAtt:
              - ParameterStoreDynamoDBRole
              - Arn
          Action:
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey*
          - kms:DescribeKey
          Resource: '*'
  ChatappTokensTableTokens:
    Type: AWS::Serverless::SimpleTable
    TableName:
      Ref: ChatappTokensTableNameTokens
    PrimaryKey:
      Name: id
      Type: String
    ProvisionedThroughput:
      ReadCapacityUnit: 5
      WriteCapacityUnits: 5
  ChatappTokensTableScheduler:
    Type: AWS::Serverless::SimpleTable
    TableName:
      Ref: ChatappTokensTableNameScheduler
    PrimaryKey:
      Name: id
      Type: String
    ProvisionedThroughput:
      ReadCapacityUnit: 5
      WriteCapacityUnits: 5
  ChatappTokensRenewStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        Fn::Sub:
        - '{ "Comment": "An example of the Amazon States Language using wait states",
          "StartAt": "Wait", "States": { "Wait": { "Type": "Wait", "SecondsPath":
          "$.waitSeconds", "Next": "InvokeRenew" }, "InvokeRenew": { "Type": "Task",
          "Resource": "${RenewFunctionArn}", "Parameters": { "Payload": { "externalId.$":
          "$.externalId", "provider.$": "$.provider" } }, "End": true } } }'
        - RenewFunctionArn:
            Fn::GetAtt:
            - RenewTokenFunctionStateMachine
            - Arn
      RoleArn:
        Fn::GetAtt:
        - ParameterStoreDynamoDBRole
        - Arn
      StateMachineName:
        Ref: RenewStateMachineName
      StateMachineType: STANDARD
