version: 2.1
orbs:
  sam: circleci/aws-sam-serverless@1.0.1
jobs:
  test_my_api:
    executor: sam/default
    steps:
      - run: echo "Run your tests here"
parameters:
  s3-bucket:
    description: Bucket to upload the SAM package to.
    type: string
    default: nexmo-tokens
workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy-staging
          stack-name: staging-stack
          template: sam-cli-template.yaml
          s3-bucket: << pipeline.parameters.s3-bucket >>
      - test_my_api:
          requires:
            - deploy-staging
      - sam/deploy:
          name: deploy-production
          requires:
            - test_my_api
          stack-name: production-stack
          template: sam-cli-template.yaml
          s3-bucket: << pipeline.parameters.s3-bucket >>
