version: 2.1
orbs:
  sam: circleci/aws-sam-serverless@1.0.1
jobs:
  test_my_api:
    executor: sam/default
    steps:
      - run: echo "Run your tests here"
  gradle_build:
    executor: sam/default
    steps:
      - run: "./gradlew shadowJar"
  deploy_without_build:
    executor: sam/default
    steps:
      - sam/deploy:
          name: deploy-staging
          stack-name: staging-stack
          template: sam-cli-template.yaml
          use-container: true
          debug: true
          s3-bucket: << pipeline.parameters.s3-bucket >>
parameters:
  s3-bucket:
    description: Bucket to upload the SAM package to.
    type: string
    default: nexmo-tokens
workflows:
  test_and_deploy:
    jobs:
      - gradle_build:
          name: gradle-build
      - deploy_without_build:
          name: deploy-staging
          requires:
            - gradle-build
      - test_my_api:
          requires:
            - deploy-staging
      - deploy_without_build:
          name: deploy-production
          requires:
            - test_my_api
